/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dataMain;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class StudentsForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentsForm
     */
    ArrayList<Student> students;
    
    private StudentApi apiStudent;
    
    
    public Student getSelectedStudent(){
    
     int index = this.jTblStudents.getSelectedRow();
     
     Student student = this.students.get(index);
     
     return student;
        
    }
  
    
    public void updateStudentTable(){
    
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Cedula");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        
        this.students = apiStudent.getStudents();
        
        for(Student student : students){
        
        model.addRow(new Object[]{
        student.getCardID(),
        student.getName(),
        student.getLastName()
        });
        
        }
        
        this.jTblStudents.setModel(model);
    
    }
    
    
    public StudentsForm() {
        apiStudent = new StudentApi();
      
        initComponents();
        updateStudentTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblStudents = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTxtSearchByCardID = new javax.swing.JTextField();
        jBtnAddStudent = new javax.swing.JButton();
        jBtnUpdateStudent = new javax.swing.JButton();
        jBtnDeleteStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jTblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblStudents);

        jLabel1.setText("Buscar Estudiante Por Cedula");

        jTxtSearchByCardID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtSearchByCardIDKeyReleased(evt);
            }
        });

        jBtnAddStudent.setText("Agregar");
        jBtnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddStudentActionPerformed(evt);
            }
        });

        jBtnUpdateStudent.setText("Actualizar");
        jBtnUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateStudentActionPerformed(evt);
            }
        });

        jBtnDeleteStudent.setText("Eliminar");
        jBtnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSearchByCardID, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBtnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(93, 93, 93)
                            .addComponent(jBtnUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtSearchByCardID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAddStudent)
                    .addComponent(jBtnUpdateStudent)
                    .addComponent(jBtnDeleteStudent))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddStudentActionPerformed
     AddUpdateStudent formInfo = new AddUpdateStudent(this, apiStudent);
     
     this.setVisible(false);
     formInfo.setVisible(true);
    }//GEN-LAST:event_jBtnAddStudentActionPerformed

    private void jBtnUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateStudentActionPerformed
       
        Student student = this.getSelectedStudent();
        AddUpdateStudent formInfo = new AddUpdateStudent(student,this, apiStudent);
     
     this.setVisible(false);
     formInfo.setVisible(true);
    }//GEN-LAST:event_jBtnUpdateStudentActionPerformed

    private void jBtnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteStudentActionPerformed
    
        int option = JOptionPane.showConfirmDialog(null,"¿Esta seguro de eliminar este estudiante?");
      
        
        if(option == JOptionPane.YES_OPTION){
        
            Student current = this.getSelectedStudent();
           String result= this.apiStudent.deleteStudent(current.getCardID());
            JOptionPane.showMessageDialog(null,result);
            this.updateStudentTable();
        }
        
        
        
    }//GEN-LAST:event_jBtnDeleteStudentActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void jTxtSearchByCardIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtSearchByCardIDKeyReleased
    String cardID = this.jTxtSearchByCardID.getText();
        System.out.println(cardID);
        
        System.out.println("Separador -----------------");
    if(!cardID.isEmpty()){
    
           DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Cedula");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        
        try {
            this.students = apiStudent.getStudentsByCardID(cardID);
        } catch (Exception ex) {
            Logger.getLogger(StudentsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for(Student student : students){
        
        model.addRow(new Object[]{
        student.getCardID(),
        student.getName(),
        student.getLastName()
        });
        
        }
        
        this.jTblStudents.setModel(model);
        
    }else{
    updateStudentTable();
    }
    
    }//GEN-LAST:event_jTxtSearchByCardIDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddStudent;
    private javax.swing.JButton jBtnDeleteStudent;
    private javax.swing.JButton jBtnUpdateStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblStudents;
    private javax.swing.JTextField jTxtSearchByCardID;
    // End of variables declaration//GEN-END:variables
}
